/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/GMGlznx4hDM
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import {Link} from "react-router-dom"

export  function Log() {
  return (
    (<div className="flex justify-center items-center h-screen">
      <div className="bg-background p-8 rounded-lg shadow-lg w-full max-w-md">
        <div className="space-y-4">
          <h1 className="text-3xl font-bold text-center">Welcome Back</h1>
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" type="email" placeholder="m@example.com" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="password">Password</Label>
            <Input id="password" type="password" />
          </div>
          <Button type="submit" className="w-full bg-blue-600">
            Login
          </Button>
          <div className="text-center text-muted-foreground">
            Don't have an account?{" "}
            <Link to="/signup" className="font-medium underline" prefetch={false}>
              Sign Up
            </Link>
          </div>
        </div>
      </div>
    </div>)
  );
}
