/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/W9shpEWpy59
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import {Link} from "react-router-dom"

export function Sigup() {
  return (
    (<div className="flex items-center justify-center outline-style: solid h-screen bg-background">
      <div className="w-full max-w-md p-6 bg-card  rounded-lg shadow-lg">
        <div className="text-center">
          <h1 className="text-3xl font-bold mb-4">Sign Up</h1>
          <p className="text-muted-foreground">Create your account</p>
        </div>

        <form className="space-y-4 mt-6">
          <div>
            <Label htmlFor="name">Name</Label>
            <Input id="name" type="text" placeholder="Enter your name" required />
          </div>
          <div>
            <Label htmlFor="email">Email</Label>
            <Input id="email" type="email" placeholder="Enter your email" required />
          </div>
          <div>
            <Label htmlFor="password">Password</Label>
            <Input id="password" type="password" placeholder="Enter your password" required />
          </div>
          <Button type="submit" className="w-full bg-blue-600">
            Sign Up

          </Button>
        </form>
        <div className="text-center mt-4 text-sm text-muted-foreground">
          Already have an account?{" "}
          <Link to="/login" className="text-primary underline" prefetch={false}>
            Login
          </Link>
        </div>
      </div>
    </div>)
  );
}
